# Generated by Django 2.0.12 on 2019-12-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_url_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_details',
            name='total_score',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
