# Generated by Django 2.0.12 on 2019-12-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_url_details_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='job_data_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
