# Generated by Django 2.0.12 on 2020-01-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quote_job_data_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
    ]
