# Generated by Django 2.0.12 on 2020-01-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200102_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_details',
            name='job_data_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
