# Generated by Django 2.0.12 on 2020-04-11 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_timetocrawl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_details',
            name='site_name',
            field=models.CharField(max_length=1000, validators=[django.core.validators.URLValidator()]),
        ),
    ]
