# Generated by Django 2.0.12 on 2020-08-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200823_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent_runs',
            name='average_score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recent_runs',
            name='average_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
